#!/usr/bin/env bash
#
# Advertise a CUPS queue to iPhones and iPads as an AirPrint printer.
#
#   sudo ./scripts/airprint.sh [queue]
#
# CUPS does advertise queues over DNS-SD on its own, but iOS is fussy: it only
# offers a printer that publishes the right TXT records, in particular a URF
# line describing the raster format it accepts. Writing the Avahi service file
# ourselves is the dependable way to get that right.

set -euo pipefail

QUEUE="${1:-labels}"
SERVICE="/etc/avahi/services/AirPrint-${QUEUE}.service"

[[ $EUID -eq 0 ]] || { echo "run this with sudo" >&2; exit 1; }

command -v lpstat >/dev/null || { echo "CUPS is not installed" >&2; exit 1; }

if ! lpstat -p "$QUEUE" >/dev/null 2>&1; then
    echo "warning: queue '$QUEUE' does not exist yet; writing the record anyway" >&2
fi

mkdir -p /etc/avahi/services

# URF describes the raster iOS may send us:
#   V1.4   URF version
#   W8     8-bit greyscale, which is what our filter consumes
#   RS203  203 dpi, the printer's native resolution
#   DM1    no duplex
#   CP1    one copy per job at the protocol level
cat > "$SERVICE" <<EOF
<?xml version="1.0" standalone='no'?>
<!DOCTYPE service-group SYSTEM "avahi-service.dtd">
<!-- Generated by scripts/airprint.sh -->
<service-group>
  <name replace-wildcards="yes">Label Printer @ %h</name>

  <service>
    <type>_ipp._tcp</type>
    <subtype>_universal._sub._ipp._tcp</subtype>
    <port>631</port>
    <txt-record>txtvers=1</txt-record>
    <txt-record>qtotal=1</txt-record>
    <txt-record>rp=printers/${QUEUE}</txt-record>
    <txt-record>ty=Thermal Label Printer</txt-record>
    <txt-record>note=4x6 shipping labels</txt-record>
    <txt-record>product=(Label Printer)</txt-record>
    <txt-record>printer-state=3</txt-record>
    <txt-record>printer-type=0x800900</txt-record>
    <txt-record>Transparent=T</txt-record>
    <txt-record>Binary=T</txt-record>
    <txt-record>TBCP=F</txt-record>
    <txt-record>Color=F</txt-record>
    <txt-record>Duplex=F</txt-record>
    <txt-record>pdl=application/pdf,image/urf,image/jpeg,application/octet-stream</txt-record>
    <txt-record>URF=V1.4,W8,RS203,DM1,CP1</txt-record>
    <txt-record>adminurl=http://%h.local:631/printers/${QUEUE}</txt-record>
  </service>
</service-group>
EOF

chmod 644 "$SERVICE"
echo "wrote $SERVICE"

if systemctl is-active --quiet avahi-daemon; then
    systemctl reload avahi-daemon 2>/dev/null || systemctl restart avahi-daemon
    echo "reloaded avahi-daemon"
fi

echo
echo "The printer should now show up in the iOS print sheet as"
echo "  Label Printer @ $(hostname -s)"
