#!/usr/bin/env python3
"""
Generate cups/LabelPrinter.ppd.

Written from scratch rather than adapted from the vendor PPD so we control the
media list and the filter chain. Run after changing LABEL_SIZES:

    python3 scripts/make_ppd.py [output.ppd]
"""

import math
import sys
from pathlib import Path

DPI = 203
DEFAULT_SIZE = "4x6.Fullbleed"

# (ppd_name, width_pt, height_pt, menu text). 1in = 72pt.
#
# These use Adobe standard media names, which is what cupstestppd wants and
# what lets CUPS map each size onto a proper IPP/PWG media name -- that is how
# an iPhone ends up offering "4 x 6 in" in the AirPrint sheet. Fullbleed
# variants declare no unprintable margins, which is right for thermal labels.
LABEL_SIZES = [
    ("4x6.Fullbleed", 288, 432, '4.00x6.00" (shipping label)'),
    ("4x8.Fullbleed", 288, 576, '4.00x8.00"'),
    ("4x4.Fullbleed", 288, 288, '4.00x4.00"'),
    ("3x5.Fullbleed", 216, 360, '3.00x5.00"'),
    ("2.25x4.Fullbleed", 162, 288, '2.25x4.00"'),
    ("2x4.Fullbleed", 144, 288, '2.00x4.00"'),
    ("100x150mm.Fullbleed", 283, 425, "100mm x 150mm"),
]

HEADER = '''*PPD-Adobe: "4.3"
*%
*% PPD for a generic 203dpi USB thermal label printer that speaks TSPL.
*% The stock vendor driver ships an x86_64-only binary filter, so this PPD
*% routes rasters through our own rastertotspl instead.
*%
*% Generated by scripts/make_ppd.py -- edit that, not this file.
*%
*FormatVersion: "4.3"
*FileVersion: "1.0"
*LanguageVersion: English
*LanguageEncoding: ISOLatin1
*PCFileName: "labeltsp.ppd"
*Manufacturer: "LabelPrinter"
*Product: "(Label Printer)"
*ModelName: "Thermal Label Printer TSPL"
*ShortNickName: "Thermal Label Printer"
*NickName: "Thermal Label Printer TSPL"
*PSVersion: "(3010.000) 550"
*PSVersion: "(3010.000) 705"
*LanguageLevel: "3"
*ColorDevice: False
*DefaultColorSpace: Gray
*FileSystem: False
*Throughput: "1"
*LandscapeOrientation: Plus90
*TTRasterizer: Type42
*cupsVersion: 1.2
*cupsManualCopies: False
*cupsModelNumber: 20
*cupsFilter: "application/vnd.cups-raster 0 rastertotspl"
*% Tells CUPS what raster iOS may send us, so the queue advertises itself as
*% AirPrint-capable: 8-bit greyscale at 203dpi, no duplex.
*cupsUrfSupported: "V1.4,W8,RS203,DM1,CP1"

*OpenGroup: General/General
'''

FOOTER = '''*CloseGroup: General/General

*DefaultFont: Courier
*Font Courier: Standard "(1.05)" Standard ROM
*Font Helvetica: Standard "(1.05)" Standard ROM
*Font Times-Roman: Standard "(1.05)" Standard ROM

*% End of LabelPrinter.ppd
'''


def option(name, label, default, choices, order=10):
    """Render one PPD PickOne option block."""
    out = [f"*OpenUI *{name}/{label}: PickOne",
           f"*OrderDependency: {order} AnySetup *{name}",
           f"*Default{name}: {default}"]
    for value, text in choices:
        out.append(f'*{name} {value}/{text}: ""')
    out.append(f"*CloseUI: *{name}")
    return "\n".join(out) + "\n\n"


def build():
    parts = [HEADER]

    # --- Media sizes -----------------------------------------------------
    sizes = LABEL_SIZES

    parts.append("*OpenUI *PageSize/Media Size: PickOne\n"
                 "*OrderDependency: 10 AnySetup *PageSize\n"
                 f"*DefaultPageSize: {DEFAULT_SIZE}\n")
    for key, w, h, name in sizes:
        parts.append(f'*PageSize {key}/{name}: '
                     f'"<</PageSize[{w} {h}]/ImagingBBox null>>setpagedevice"\n')
    parts.append("*CloseUI: *PageSize\n\n")

    parts.append("*OpenUI *PageRegion/Media Size: PickOne\n"
                 "*OrderDependency: 10 AnySetup *PageRegion\n"
                 f"*DefaultPageRegion: {DEFAULT_SIZE}\n")
    for key, w, h, name in sizes:
        parts.append(f'*PageRegion {key}/{name}: '
                     f'"<</PageSize[{w} {h}]/ImagingBBox null>>setpagedevice"\n')
    parts.append("*CloseUI: *PageRegion\n\n")

    # Thermal labels print edge to edge -- no unprintable margins.
    parts.append(f"*DefaultImageableArea: {DEFAULT_SIZE}\n")
    for key, w, h, name in sizes:
        parts.append(f'*ImageableArea {key}/{name}: "0 0 {w} {h}"\n')
    parts.append("\n")

    parts.append(f"*DefaultPaperDimension: {DEFAULT_SIZE}\n")
    for key, w, h, name in sizes:
        parts.append(f'*PaperDimension {key}/{name}: "{w} {h}"\n')
    parts.append("\n")

    # --- Resolution ------------------------------------------------------
    # cupsColorSpace 0 = gray, 8 bits per colour: exactly what our filter wants.
    parts.append(
        "*OpenUI *Resolution/Resolution: PickOne\n"
        "*OrderDependency: 20 AnySetup *Resolution\n"
        f"*DefaultResolution: {DPI}dpi\n"
        f'*Resolution {DPI}dpi/{DPI} dpi: '
        f'"<</HWResolution[{DPI} {DPI}]/cupsBitsPerColor 8/cupsRowCount 8'
        '/cupsRowFeed 0/cupsRowStep 0/cupsColorSpace 0>>setpagedevice"\n'
        "*CloseUI: *Resolution\n\n"
    )

    # --- Printer knobs, read back by rastertotspl ------------------------
    parts.append(option(
        "Darkness", "Darkness", "6",
        [(str(i), str(i)) for i in range(16)], order=30))

    parts.append(option(
        "zePrintRate", "Print Speed", "4",
        [(str(i), f"{i} in/s") for i in (1, 2, 3, 4, 5, 6)], order=30))

    parts.append(option(
        "zeMediaTracking", "Media Tracking", "Gap",
        [("Gap", "Gap-separated labels"),
         ("Continuous", "Continuous stock")], order=30))

    parts.append(option(
        "AdjustHorizontal", "Horizontal Offset (dots)", "0",
        [(str(v), str(v)) for v in range(-24, 25, 4)], order=40))

    parts.append(option(
        "AdjustVertical", "Vertical Offset (dots)", "0",
        [(str(v), str(v)) for v in range(-24, 25, 4)], order=40))

    parts.append(FOOTER)
    return "".join(parts)


def main(argv=None):
    argv = sys.argv[1:] if argv is None else argv

    if argv:
        dest = Path(argv[0])
    else:
        dest = Path(__file__).resolve().parent.parent / "cups" / "LabelPrinter.ppd"
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(build())

    # Sanity check the geometry our filter will be handed.
    w, h = 288, 432
    print(f"wrote {dest}")
    print(f"  default media {DEFAULT_SIZE}: {w}x{h}pt -> "
          f"{round(w / 72 * DPI)}x{round(h / 72 * DPI)} dots @ {DPI}dpi -> "
          f"{math.ceil(w * 25.4 / 72)}x{math.ceil(h * 25.4 / 72)}mm")
    print(f"  {len(LABEL_SIZES)} media sizes")


if __name__ == "__main__":
    main()
